### ISSUE TITLE
Couldn't find a project to run

### ISSUE THREAD

**Issue by t4trust** [neozhu/cleanaspire#3]
Couldn't find a project to run. Ensure a project exists in C:\Users\user\source\repos\cleanaspire, or pass the path to the project using --project.

**Comment by neozhu** [comment]
![image](https://github.com/user-attachments/assets/74522dd1-2abb-4c4d-8dab-772e75ba661f)
![image](https://github.com/user-attachments/assets/c78d3706-30c5-41b7-984d-f072b46799d3)

![image](https://github.com/user-attachments/assets/197828e9-28a1-4d15-9d43-97069d077714)
