### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by 274188A** [neozhu/cleanaspire#4]
Key Issues
Dependency Constraint Warnings:

Warning NU1608: EFCore.NamingConventions 8.0.3 is incompatible with Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.Relational version 9.0.0.
This indicates a mismatch between the versions of EFCore.NamingConventions and EntityFrameworkCore packages.
DirectoryNotFoundException:

The directory ...\***\cleanaspire\src\CleanAspire.Api\files\ does not exist but is being referenced by the Microsoft.Extensions.ApiDescription.Server package.
MSBuild Command Failure:

The command to generate OpenAPI documentation (via dotnet-getdocument) failed due to the above issues.

**Comment by 274188A** [comment]
suggest adding an empty dir in the source to fix the error.

**Comment by neozhu** [comment]
please try it again
