### ISSUE TITLE
Build Warnings

### ISSUE THREAD

**Issue by 274188A** [neozhu/cleanaspire#5]
Severity	Code	Description	Project	File	Line	Suppression State
Warning (active)	CS8622	Nullability of reference types in type of parameter 'value' of 'Task<IEnumerable<string>> LanguageAutocomplete<T>.SearchFunc_(string value, CancellationToken cancellation = default(CancellationToken))' doesn't match the target delegate 'Func<string?, CancellationToken, Task<IEnumerable<string>>?>' (possibly because of nullability attributes).	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Components\Autocompletes\LanguageAutocomplete.cs	10	
Warning (active)	CS8622	Nullability of reference types in type of parameter 'value' of 'Task<IEnumerable<string>> TimeZoneAutocomplete<T>.SearchFunc_(string value, CancellationToken cancellation = default(CancellationToken))' doesn't match the target delegate 'Func<string?, CancellationToken, Task<IEnumerable<string>>?>' (possibly because of nullability attributes).	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Components\Autocompletes\TimeZoneAutocomplete.cs	9	
Warning (active)	BL0007	Component parameter 'CleanAspire.ClientApp.Components.LoadingButton.MudLoadingButton.Loading' should be auto property	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Components\LoadingButton\MudLoadingButton.razor	69	
Warning (active)	CS8618	Non-nullable property 'ChildContent' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Components\LoadingButton\MudLoadingButton.razor	82	
Warning (active)	CS8618	Non-nullable property 'LoadingContent' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Components\LoadingButton\MudLoadingButton.razor	85	
Warning (active)	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Account\EmailChangeConfirm.razor	90	
Warning (active)	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Account\ForgetPasswordConfirm.razor	91	
Warning (active)	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Account\Profile\AccountSetting.razor	76	
Warning (active)	CS8602	Dereference of a possibly null reference.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Account\Profile\AccountSetting.razor	87	
Warning (active)	CS8618	Non-nullable field 'browserFile' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the field as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Account\Profile\ProfileSetting.razor	52	
Warning (active)	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Account\Profile\ProfileSetting.razor	58	
Warning (active)	CS8601	Possible null reference assignment.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Account\Profile\ProfileSetting.razor	66	
Warning (active)	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Account\SignupConfirmation.razor	26	
Warning (active)	CS0105	The using directive for 'CleanAspire.Api.Client.Models' appeared previously in this namespace	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Account\_Imports.razor	2	
Warning (active)	CS8618	Non-nullable property 'OrderNumber' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Home.razor	262	
Warning (active)	CS8618	Non-nullable property 'Currency' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Home.razor	264	
Warning (active)	CS8618	Non-nullable property 'Status' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Home.razor	265	
Warning (active)	CS8618	Non-nullable property 'OverdueStatus' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Home.razor	266	
Warning (active)	CS8618	Non-nullable property 'CustomerName' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Home.razor	268	
Warning (active)	CS8618	Non-nullable property 'ShippingAddress' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Home.razor	269	
Warning (active)	CS8618	Non-nullable property 'Product' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Pages\Home.razor	270	
Warning (active)	CS8634	The type 'CleanAspire.ClientApp.Configurations.ClientAppSettings?' cannot be used as type parameter 'TService' in the generic type or method 'ServiceCollectionServiceExtensions.AddSingleton<TService>(IServiceCollection, TService)'. Nullability of type argument 'CleanAspire.ClientApp.Configurations.ClientAppSettings?' doesn't match 'class' constraint.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Program.cs	27	
Warning (active)	CS0618	'IDialogService.Show<TComponent>(string?, DialogParameters, DialogOptions?)' is obsolete: 'Use ShowAsync instead. This will be removed in future major version.'	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\DialogServiceHelper.cs	30	
Warning (active)	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\Identity\AccessTokenProvider.cs	22	
Warning (active)	CS0414	The field 'CookieAuthenticationStateProvider.authenticated' is assigned but its value is never used	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\Identity\CookieAuthenticationStateProvider.cs	16	
Warning (active)	CS8604	Possible null reference argument for parameter 'value' in 'Claim.Claim(string type, string value)'.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\Identity\CookieAuthenticationStateProvider.cs	36	
Warning (active)	CS8604	Possible null reference argument for parameter 'value' in 'Claim.Claim(string type, string value)'.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\Identity\CookieAuthenticationStateProvider.cs	37	
Warning (active)	CS8604	Possible null reference argument for parameter 'value' in 'Claim.Claim(string type, string value)'.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\Identity\CookieAuthenticationStateProvider.cs	38	
Warning (active)	CS8618	Non-nullable property 'Userid' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\UserInfo.cs	5	
Warning (active)	CS8618	Non-nullable property 'Username' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\UserInfo.cs	6	
Warning (active)	CS8618	Non-nullable property 'Nickname' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\UserInfo.cs	7	
Warning (active)	CS8618	Non-nullable property 'Email' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\UserInfo.cs	9	
Warning (active)	CS8618	Non-nullable property 'Token' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\UserInfo.cs	10	
Warning (active)	CS8618	Non-nullable property 'Role' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\Services\UserInfo.cs	11	
Warning (active)	CS0108	'MudEnumSelect<TEnum>.Logger' hides inherited member 'MudComponentBase.Logger'. Use the new keyword if hiding was intended.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\_Imports.razor	30	
Warning (active)	CS0108	'MudLoadingButton.Logger' hides inherited member 'MudComponentBase.Logger'. Use the new keyword if hiding was intended.	CleanAspire.ClientApp	D:\repos\cleanaspire\src\CleanAspire.ClientApp\_Imports.razor	30	
Warning (active)	CS8618	Non-nullable property 'Id' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.	CleanAspire.Domain	D:\repos\cleanaspire\src\CleanAspire.Domain\Entities\AuditTrail.cs	13	
Warning (active)	NU1608	Detected package version outside of dependency constraint: EFCore.NamingConventions 8.0.3 requires Microsoft.EntityFrameworkCore (>= 8.0.0 && < 9.0.0) but version Microsoft.EntityFrameworkCore 9.0.0 was resolved.	CleanAspire.Infrastructure	D:\repos\cleanaspire\src\CleanAspire.Infrastructure\CleanAspire.Infrastructure.csproj	1	
Warning (active)	NU1608	Detected package version outside of dependency constraint: EFCore.NamingConventions 8.0.3 requires Microsoft.EntityFrameworkCore.Relational (>= 8.0.0 && < 9.0.0) but version Microsoft.EntityFrameworkCore.Relational 9.0.0 was resolved.	CleanAspire.Infrastructure	D:\repos\cleanaspire\src\CleanAspire.Infrastructure\CleanAspire.Infrastructure.csproj	1	
Warning (active)	NU1608	Detected package version outside of dependency constraint: EFCore.NamingConventions 8.0.3 requires Microsoft.EntityFrameworkCore (>= 8.0.0 && < 9.0.0) but version Microsoft.EntityFrameworkCore 9.0.0 was resolved.	Migrators.MSSQL	D:\repos\cleanaspire\src\Migrators\Migrators.MSSQL\Migrators.MSSQL.csproj	1	
Warning (active)	NU1608	Detected package version outside of dependency constraint: EFCore.NamingConventions 8.0.3 requires Microsoft.EntityFrameworkCore.Relational (>= 8.0.0 && < 9.0.0) but version Microsoft.EntityFrameworkCore.Relational 9.0.0 was resolved.	Migrators.MSSQL	D:\repos\cleanaspire\src\Migrators\Migrators.MSSQL\Migrators.MSSQL.csproj	1	
Warning (active)	NU1608	Detected package version outside of dependency constraint: EFCore.NamingConventions 8.0.3 requires Microsoft.EntityFrameworkCore (>= 8.0.0 && < 9.0.0) but version Microsoft.EntityFrameworkCore 9.0.0 was resolved.	Migrators.PostgreSQL	D:\repos\cleanaspire\src\Migrators\Migrators.PostgreSQL\Migrators.PostgreSQL.csproj	1	
Warning (active)	NU1608	Detected package version outside of dependency constraint: EFCore.NamingConventions 8.0.3 requires Microsoft.EntityFrameworkCore.Relational (>= 8.0.0 && < 9.0.0) but version Microsoft.EntityFrameworkCore.Relational 9.0.0 was resolved.	Migrators.PostgreSQL	D:\repos\cleanaspire\src\Migrators\Migrators.PostgreSQL\Migrators.PostgreSQL.csproj	1	
Warning (active)	NU1608	Detected package version outside of dependency constraint: EFCore.NamingConventions 8.0.3 requires Microsoft.EntityFrameworkCore (>= 8.0.0 && < 9.0.0) but version Microsoft.EntityFrameworkCore 9.0.0 was resolved.	Migrators.SQLite	D:\repos\cleanaspire\src\Migrators\Migrators.SQLite\Migrators.SQLite.csproj	1	
Warning (active)	NU1608	Detected package version outside of dependency constraint: EFCore.NamingConventions 8.0.3 requires Microsoft.EntityFrameworkCore.Relational (>= 8.0.0 && < 9.0.0) but version Microsoft.EntityFrameworkCore.Relational 9.0.0 was resolved.	Migrators.SQLite	D:\repos\cleanaspire\src\Migrators\Migrators.SQLite\Migrators.SQLite.csproj	1	
Warning (active)	NU1608	Detected package version outside of dependency constraint: EFCore.NamingConventions 8.0.3 requires Microsoft.EntityFrameworkCore (>= 8.0.0 && < 9.0.0) but version Microsoft.EntityFrameworkCore 9.0.0 was resolved.	CleanAspire.Api	D:\repos\cleanaspire\src\CleanAspire.Api\CleanAspire.Api.csproj	1	
Warning (active)	NU1608	Detected package version outside of dependency constraint: EFCore.NamingConventions 8.0.3 requires Microsoft.EntityFrameworkCore.Relational (>= 8.0.0 && < 9.0.0) but version Microsoft.EntityFrameworkCore.Relational 9.0.0 was resolved.	CleanAspire.Api	D:\repos\cleanaspire\src\CleanAspire.Api\CleanAspire.Api.csproj	1

**Comment by neozhu** [comment]
Warnings can be ignored. I am waiting for EFCore.NamingConventions upgrade to dotnet 9
